version: '3.3'
services:
  brocast_app:
    image: node:22.5-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "32869:32869"
    environment:
      - NODE_ENV=development
      - PORT=32869
      - HOST=0.0.0.0